---
# supported frameworks: mocha|jest|jasmine
framework: mocha

preRun:
  command:
    - npm i

postMerge:
  pattern:
    - "**/*.spec.ts"
  # strategy for trigerring builds for post-merge

preMerge:
  pattern:
    - "**/*.spec.ts"

# configure whether to smartSelect test-cases. Default true
smartRun: true

# number of containers in which the tests must be splitted into for execution
parallelism: 1

# version of tas file intended to be used in order to issue warnings for deprecation or breaking changes
version: 1.0.0
